Supabaseに連携データをアップロードする機能の実装
Aoichaan0513/FSLink pull request #3
Opened 2021-12-12 03:48 UTC by Alpha9n

連携・解除時にそれぞれSupabase側にアップロード・削除をする機能を実装しました 既にあったConfigの読み書きの機能は削除していません

2021-12-14 00:58 UTC, Aoichaan0513 requested changes
いつの間にPostgreSQLなんて使うようになったんだ…

## 全体的に
Null安全な方法でのコード記述をできる限りしてほしいです。
`!!` -> `?.` やエルビス演算子の利用、早期リターンでの解決など、必ずNullにならないことが分かっている場合でも、念のためにそれらを利用するなどしてください。

## `build.gradle`
依存関係の記述を分ける感じのやつに統一してください。
この形式:
```gradle
implementation group: 'グループ名', name: 'アーティファクト名', version: 'バージョン'
```

## `MainAPI.kt`
全体的なコードの整形を行ってください。 (Ctrl+Alt+L)

## `PerseAPI.kt`
ファイルとクラス名のスペルミスを修正してください。 (Shift+F6)

## `Main.kt`
恐らくCacheFlagは設定しなくても正常に動作するはずです。

2023-05-06 16:39 UTC, Aoichaan0513 approved these changes
問題ない気がしますー（ポスグレを扱ったことがないためそこまで確認できない）
余談なんですがなかなか確認などできていないので、いっその事リポジトリを移動してもいい気がしちゃいます

2023-05-11 01:59 UTC, Alpha9n commented
確認ありがとうございます！
移動の際はfreeserverprojectのorgに送ってもらえるとうれしいですー！

2023-05-11 02:09 UTC, Aoichaan0513 commented
移動しましたー
よければマージしちゃってください

2023-06-01 12:29 UTC, Alpha9n commented
めっちゃわすれてました()
ありがとうございます！
マージしておきます〜！

2023-06-01 12:29 UTC, merged